### PR TITLE
Option to upload xcresult bundle on failure only

### PR DESCRIPTION
**Pull request by Jon889**
Pretty much as the title says. It changes upload_bundle from a boolean to a string input, so that `always`, `failure` or `never` can be specified. always/never act like true/false did, and failure will only upload the xcresult if the result of the tests is failure.

### CODE REVIEW

**Comment by kishikawakatsumi** [comment]
@Jon889 Thanks for the PR! Looks like a good idea. Can you modify it that it does not change the existing behavior? I want to keep it compatible with previous versions.
I mean I would like the values to take `true`, `false`, `always`, `failure` and `never`, and make `true` and `always`, `false` and `never` mean the same thing.

**Comment by Jon889** [comment]
ah good point! I've made a change, but JS is not the primary language I know so not sure if there's a more idiomatic way of doing it, if you have a better suggestion I'm happy to make it :)

**Comment by kishikawakatsumi** [comment]
Seems good. I'll merge this later soon. Thank you 👍🏻

**Comment by kishikawakatsumi** [comment]
@Jon889 Released as 1.7.0. Thank you for contribution!!

**Pull request merged**
